package com.jiyun.zuoye1.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;


import com.jiyun.zuoye1.bean.AndroidBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig androidBeanDaoConfig;

    private final AndroidBeanDao androidBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        androidBeanDaoConfig = daoConfigMap.get(AndroidBeanDao.class).clone();
        androidBeanDaoConfig.initIdentityScope(type);

        androidBeanDao = new AndroidBeanDao(androidBeanDaoConfig, this);

        registerDao(AndroidBean.class, androidBeanDao);
    }
    
    public void clear() {
        androidBeanDaoConfig.clearIdentityScope();
    }

    public AndroidBeanDao getAndroidBeanDao() {
        return androidBeanDao;
    }

}
